In [7]:
import torch

In [8]:
import numpy as np

In [9]:
tensor_1 = torch.tensor(5)

In [10]:
print(tensor_1)

tensor(5)


In [11]:
print(tensor_1.dtype)

torch.int64


In [12]:
tensor_2 = torch.tensor([1,2,3,4,5],dtype=torch.float32)

In [13]:
print(tensor_2)

tensor([1., 2., 3., 4., 5.])


In [14]:
print(tensor_2.shape)

torch.Size([5])


In [15]:
print(tensor_2.size())

torch.Size([5])


In [16]:
n1 = np.array([1,2,3,4,5])

In [17]:
n1

array([1, 2, 3, 4, 5])

In [18]:
t1_from_n1 = torch.from_numpy(n1)

In [19]:
print(t1_from_n1)

tensor([1, 2, 3, 4, 5])


In [20]:
t_from_rand = torch.randint(1,10, (2,3))

In [21]:
print(t_from_rand)

tensor([[1, 4, 8],
        [1, 6, 6]])
