In [1]:
import torch 

In [2]:
t1 = torch.zeros(100)

In [3]:
t1.shape

torch.Size([100])

In [ ]:
t1

In [ ]:
t2 = torch.reshape(t1,(5,20))

In [ ]:
t2.shape

In [ ]:
t2

In [ ]:
t4 = torch.randint(1,20,(4,3),dtype=torch.float16)

In [ ]:
t4

In [ ]:
t5 = torch.mean(t4,0)

In [ ]:
t5

In [ ]:
torch.mean(t4,1)

In [ ]:
t4 = torch.randint(1,20,(4,3),dtype=torch.float16)

In [ ]:
t4

In [ ]:
t6 =torch.sum(t4,0)

In [ ]:
t6

In [ ]:
t7 = torch.std(t4,0)

In [ ]:
t7

In [ ]:
t4

In [ ]:
t7 = torch.randint(1,10,(3,1))

In [ ]:
t7

In [ ]:
t7.shape

In [2]:
t9 = torch.randint(1,30,(3,4))

In [3]:
t9

tensor([[27, 12, 28, 22],
        [27, 15, 11, 21],
        [10, 25, 10, 24]])

In [7]:
type(torch.split(t9,1))

tuple

In [8]:
torch.split(t9,2)[0].shape

torch.Size([2, 4])

In [10]:
torch.split(t9,3)[0].shape

torch.Size([3, 4])

In [9]:
t1 = torch.ones(3)

In [154]:
t2 = torch.zeros(3)

In [155]:
t1

tensor([1., 1., 1.])

In [156]:
t2

tensor([0., 0., 0.])

In [157]:
t3 = torch.cat((t1,t2))

In [158]:
t3

tensor([1., 1., 1., 0., 0., 0.])

In [159]:
t3.shape

torch.Size([6])

In [161]:
t4 = torch.stack((t1,t2))

In [162]:
t4

tensor([[1., 1., 1.],
        [0., 0., 0.]])

In [163]:
t4.shape

torch.Size([2, 3])

In [164]:
t4[0].shape

torch.Size([3])

In [165]:
t2.shape

torch.Size([3])